app/views/views.py
from flask import Blueprint, abort
from flask import redirect, render_template, request, url_for

from formencode import validators

from . import forms
from .models import View, Group, Filter

from ..cards.models import Card
from ..filters.forms import FilterForm

from ..database import db_session
from ..helpers import get_or_404, jsonify

mod = Blueprint('views', __name__, url_prefix='/views')

@mod.route('/')
def index():
    views = View.query
    return render_template('views/index.html', views=views)

@mod.route('/<int:id>')
def view(id):
    view = get_or_404(View, View.id==id)

    if view.type == 'tree':
        return view_tree(view)
    elif view.type == 'list':
        return view_list(view)

    return abort(404)

def view_tree(view):
    return render_template('views/tree.html', view=view, order=forms.order)

def view_list(view):
    return render_template('views/list.html', view=view, order=forms.order)

@mod.route('/<int:id>/tree')
def tree(id):
    ''' ajax request from jstree to get nodes at a given level'''
    validator = validators.Int()

    view = get_or_404(View, View.id==id)
    level = validator.to_python(request.args['level'])
    parents = [validator.to_python(p) for p in request.args.getlist('values[]')]
    tags = view.get_nodes(level+1, parents=parents)

    return jsonify(tags)

@mod.route('/all-cards')
def all_cards():
    filter_ = FilterForm(request.args)
    q = filter_.prepare_query(Card.query)
    return render_template('views/all-cards.html', cards=q, filter=filter_)

@mod.route('/new', methods=['GET', 'POST'])
def new(id=None):
    is_new = id is None
    if is_new:
        view = View()
        form = forms.ViewForm(request.form)
    else:
        view = get_or_404(View, View.id==id)
        form = forms.ViewForm(request.form, view)

    filter_ = FilterForm(request.form if request.form else view.get_filter_dict(), allow_empty=True)

    if form.validate_on_submit():
        form.populate_obj(view)

        if not is_new:
            # to make it simple, just remove all groups assigned to this view
            # otherwise, call views.groups.append(g) views.filters.remove(f)
            Group.query.filter(Group.view_id == view.id).delete()
            Filter.query.filter(Filter.view_id == view.id).delete()

        for i, o in enumerate(forms.order):
            try:
                data = form.groups.data[o.lower()]
                if not data:
                    continue

                g = Group()
                g.tag = data
                g.order = i
                view.groups.append(g)
            except KeyError:
                pass

        for i, p in enumerate(filter_.values['filters']):
            f = Filter()
            f.key = p['key']
            f.condition = p['condition']
            f.values = dict(value=p['value'], value_start=p['value_start'], value_finish=p['value_finish'])
            f.order = i
            view.filters.append(f)

        if is_new:
            db_session.add(view)

        db_session.commit()
        return redirect(url_for('.view', id=view.id))

    return render_template('views/new.html', filter=filter_, form=form, view=view)

@mod.route('/<int:id>/edit', methods=['GET', 'POST'])
def edit(id):
    return new(id)

@mod.route('/<int:id>', methods=['DELETE'])
@mod.route('/<int:id>/delete')
def delete(id):
    v = get_or_404(View, View.id==id)
    db_session.delete(v)
    db_session.commit()

    return redirect(url_for('.index'))

app/templates/views/all-cards.html
{% extends "views/base.fixed-width.html" %}
{% block content %}
<h2>All Cards</h2>

<h3>Filters</h3>
<form>
{{ filter() }}
</form>

<div id="view" class="row">
</div>
{% endblock %}

{% block css %}
{{ super() }}
<style>
{{ filter.stylesheet() }}
</style>
{% endblock %}

{% block js %}
{{ super() }}
<script>
$(function() {
    $('select').chosen();
    {# escape {{ and }} #}
    {{ filter.javascript() }}
    var cards = new models.CardList();
    $('#view').sortable({
        distance: 10,
        placeholder: 'card-placeholder',
        forcePlaceholderSize: true,
        helper: 'clone'
    });

    var CardView = Backbone.View.extend({
        tagName: 'div',
        className: 'well well-small span3',
        template: _.template($('#card-template').html()),
        events: {
            'click a': 'open_card',
            'click .caret': 'show_context_menu',
        },
        initialize: function() {
            this.listenTo(this.model, 'change', this.render);
            this.listenTo(this.model, 'destroy', this.remove);
            this.listenTo(this.model.tags, 'all', this.render);
            this.model.view = this;
        },
        render: function() {
            var m = this.model, $el = this.$el;
            var j = m.toJSON();
            j['tags'] = m.tags.toJSON();
            $el.html(this.template(j));
            $el.data({
                'view': this,
                'model': m,
            });
            $el.attr('data-id', m.id);
            return this;
        },
        show_context_menu: function(e) {
            var c = this.$el.find('.caret');
            context_menu.attach_card(this.model);
            context_menu.show(c);
            return false;
        },
        open_card: function(e) {
            e.preventDefault();
            card_form_view.show(this.model);
        }
    });

    var View = Backbone.View.extend({
        el: $('#view'),
        initialize: function() {
            this.listenTo(cards, 'add', this.addOne);
            this.listenTo(cards, 'reset', this.addAll);
        },

        addOne: function(card) {
            var v = new CardView({model: card});
            this.$el.append(v.render().el);
        },
        addAll: function(cards) {
            cards.each(this.addOne, this);
        }
    });

    var view = new View();

    {% for c in cards %}
    cards.add({{ c.__json__()|tojson|safe }});
    {% endfor %}
});
</script>
{% endblock %}

app/templates/views/base.fixed-width.html
{% extends "views/base.html" %}
{% block body %}
<div class="container">
{% block content %}{% endblock %}
</div>
{% endblock %}

app/templates/views/base.full-width.html
{% extends "views/base.html" %}

{% block body %}
{% block content %}
<h2><span>{{ view.name }}</span><a href="#info" role="button" class="btn btn-link" data-toggle="modal"><i class="icon-info-sign"></i></a></h2>
<hr />
<div id="canvas-wapper"><div id="canvas">
{% block canvas %}{% endblock %}
</div></div>
<div id="info" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">x</button>
        <h3>Information</h3>
    </div>
    <div class="modal-body">{% block info %}
        <h4>Filters</h4>
        <p>
        {% for f in view.filters%}
        <i class="icon-filter"></i> {{ f }} {% if not loop.last %}<br />{% endif %}
        {% else %}
        No filters are applied.
        {% endfor %}
        </p>

        <h4>Groups</h4>
        <p>
        {% for g in view.groups %}
        {{ order[g.order] }} level: <i class="icon-tag"></i> {{ g.tag.name }} {% if not loop.last %}<br />{% endif %}
        {% endfor %}
        </p>
        {% endblock %}</div>
    <div class="modal-footer">
        <a href="{{ url_for('views.edit', id=view.id) }}" class="btn btn-info">Update View</a>
        <button class="btn" data-dismiss="modal">Close</button>
    </div>
</div>
{% endblock %}
{% endblock %}

{% block css %}
{{ super() }}
<style>
h2 span {
    padding-left: 16px;
}
</style>
{% endblock %}

{% block js %}
{{ super() }}
{% endblock %}

app/templates/views/index.html
{% extends "base.fixed-width.html" %}

{% block content %}
<h2>Manage Views</h2>
<div class="row">
    <div class="span6">
        <table class="table table-striped">
            <thead><tr>
                <th>View</th>
                <th>Type</th>
                <th><i class="icon-cog"></i></th>
            </tr></thead>
            <tbody>
{% for v in views %}
                <tr>
                    <td><a href="{{ url_for('views.view', id=v.id) }}">{{ v.name }}</a></td>
                    <td>{{ v.type|capitalize }}</td>
                    <td>
                        <a href="{{ url_for('views.edit', id=v.id) }}" class="btn btn-mini">Update</a>
                        <a href="{{ url_for('views.delete', id=v.id) }}" class="btn btn-mini btn-danger">Remove</a>
                    </td>
                </tr>
{% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="span6"><a class="btn" href="{{ url_for('views.new') }}">New View</a></div>
</div>
{% endblock %}

app/templates/views/list.html
{% extends "views/base.full-width.html" %}

{% block css %}
{{ super() }}
<style>
#canvas {
    padding-right: 20px;
}
#canvas > div {
    background-color: #FBFBFB;
    border: 1px solid #DDDDDD;
    border-radius: 4px 4px 4px 4px;
    width: 260px;
}
#canvas > div > h3 {
    font-size: 17.5px;
    overflow: hidden;
    padding: 0 20px;
    text-overflow: ellipsis;
    white-space: nowrap;
}
</style>
{% endblock %}

{% block bodyhelpers %}
{{ super() }}
<script type="text/template" id="list-template">
    {% raw %}
    <h3 title="{{value}}">{{value}}</h3>
    <div class="cards"></div>
    {% endraw %}
</script>
{% endblock %}

{% block js %}
{{ super() }}
<script>
$(function() {
    $('#canvas').sortable({
        distance: 10,
        placeholder: 'card-placeholder',
        forcePlaceholderSize: true,
        helper: 'clone',
        items: '> div > div.cards > div[data-id]',
        update: function(e, kwargs) {
            var m = kwargs.item.data('model');
            var sender = m.list;
            var receiver = kwargs.item.parent().parent().data('view').cards;

            if (sender == receiver) { // order has changed
            } else {
                sender.remove(m);
                var at = m.view.$el.parent().children().index(m.view.$el);
                m.view.$el.remove();
                receiver.add(m, {at: at});
                m.tags.remove(sender.tag);
                m.tags.add(receiver.tag);
                m.save({tags: m.tags.map(function(t) {return t.id})});
            }
        }
    });
    var tag_list = new models.TagList();
    var cards = new (models.CardList.extend({
        _sync:function(data, e) {
            var c = this.get(data.id);
            if (c) {
                c.tags.update(data.tags, {silence: true});
                c.set(data);
            } else {
                this._add(data, e);
            }
        },
        _add:function(data, e) {
            var accept = false;
            _.each(data.tags, function(t) {
                var _t = tag_list.get(t.id);
                if (_t) {
                    accept = true;
                    return false;
                }
            });

            if (!accept) {
                return;
            }

            this.add(data);
        }
    }))();

    var _CardList = models.CardList.extend({
        initialize: function() {
            this.listenTo(this, 'add', this._add_listener);
            this.listenTo(this, 'remove', this._remove_listender);
        },
        _add_listener: function(card) {
            card.list = this;
            this.listenTo(card, 'change', this._card_change);
        },
        _remove_listender: function(card) {
            delete card.list;
            this.stopListening(card, 'change', this._card_change);
        },
        _card_change: function(card) {
            if (!card.tags.get(this.tag.id)) {
                this.remove(card);
                card.view.$el.remove();
                card.tags.each(function(t) {
                    if (tag_list.get(t.id)) {
                        tag_list.get(t.id).view.cards.add(card);
                        return false;
                    }
                });
            }
        }
    });

    var CardView = Backbone.View.extend({
        tagName: 'div',
        className: 'well well-small span3',
        template: _.template($('#card-template').html()),
        events: {
            'click .caret': 'show_context_menu',
            'click a[href]': 'open_card'
        },
        initialize: function() {
            this.listenTo(this.model, 'change', this.render);
            this.listenTo(this.model, 'destroy', this.remove);
            this.listenTo(this.model.tags, 'all', this.render);
            this.model.view = this;
        },
        render: function() {
            var m = this.model, $el = this.$el;
            var j = m.toJSON();
            j['tags'] = m.tags.toJSON();
            $el.html(this.template(j));
            $el.data({
                'view': this,
                'model': m,
            });
            $el.attr('data-id', m.id);
            return this;
        },
        show_context_menu: function(e) {
            var c = this.$el.find('.caret');
            context_menu.attach_card(this.model);
            context_menu.show(c);
            return false;
        },
        open_card: function(e) {
            e.preventDefault();
            card_form_view.show(this.model);
        }
    });

    var ListView = Backbone.View.extend({
        tagName: 'div',
        className: 'span4',
        template: _.template($('#list-template').html()),
        initialize: function() {
            this.cards = new _CardList();
            this.cards.tag = this.model;
            this.model.view = this;
            this.listenTo(cards, 'add', this.addCard);
            this.listenTo(this.cards, 'add', this.renderCard);
            this.listenTo(this.model, 'change', this.render);
        },
        render: function() {
            var m = this.model
            var $el = this.$el;
            var j = m.toJSON();
            $el.html(this.template(j)).data('view', this);
            this.cards.$el = this.$el.find('.cards');
            this.$el.data({
                view: this,
                model: this.model,
            });
            return this;
        },
        addCard: function(card) {
            var m = this.model;
            var found = card.tags.find(function(t) { return m.id == t.id});
            if (found) {
                this.cards.add(card);
            }
        },
        renderCard: function(card, collection , option) {
            var v = new CardView({model: card});
            if (_.isNumber(option.at)) {
                var prev = this.cards.$el.children(':eq(' + option.at + ')');

                if (prev.length) {
                    prev.before(v.render().el);
                    return;
                }
            }

            this.cards.$el.append(v.render().el);
        }
    });

    var View = Backbone.View.extend({
        el: $('#canvas'),
        initialize: function() {
            this.listenTo(tag_list, 'add', this.addOne);
            this.list_width = false;
        },
        addOne: function(tag) {
            var v = new ListView({model: tag});
            tag.view = v;
            this.$el.append(v.render().el);
            if (!this.list_width) {
                this.list_width = v.$el.outerWidth() + 20;
            }
            this.$el.css('width', tag_list.size() * this.list_width);
        },
        addAll: function() {
            cards.each(this.addOne, this);
        }
    });

    var view = new View();

    {% for t in view.get_tags(0) %}
    tag_list.add({{t.__json__()|tojson|safe}});
    {% endfor %}

    {% for c in view.get_cards(0) %}
    cards.add({{ c.__json__()|tojson|safe }});
    {% endfor %}


});
</script>
{% endblock %}
{% block tag_click_return %}e.preventDefault();{% endblock %}

app/templates/views/new.html
{% extends "base.fixed-width.html" %}

{% block css %}
{{ super() }}
<link href="/static/chosen/chosen/chosen.css" rel="stylesheet" media="screen">
<style>
#groups tbody tr:nth-child(1) {
    display: none;
}
{{ filter.stylesheet() }}
</style>
{% endblock %}

{% block content %}
<div class="row"><div class="span10 offset1">
<h2>{% if view and view.id %}Edit{% else %}New{% endif %} View</h2>
<form method="POST"  class="form-horizontal">
{% from "forms/macros.html" import render_field %}
{{ form.csrf_token }}
{{ render_field(form.name, class="input-xlarge") }}
{{ render_field(form.type) }}
<div>
<label class="control-label">Filter Cards On</label>
{{ filter(submit=False, class="controls") }}
</div>
{{ render_field(form.groups) }}
<div class="controls">
    <input type="submit" value="Save" class="btn btn-primary">
    {% if view and view.id %} <a href="{{ url_for('views.view', id=view.id) }}" class="btn">Cancel</a>
    {% else %} <a href="{{ url_for('views.index') }}">All Views</a> {% endif %}
</div>
</form>

</div></div>
{% endblock %}

{% block js %}
{{ super() }}
<script src="/static/chosen/chosen/chosen.jquery.min.js"></script>
<script>
$(function() {
    $('select[name^=groups]').filter(':eq(0)').chosen().end()
                             .filter(':gt(0)').chosen({allow_single_deselect: true});
     $('input[name=type]:radio').change(function() {
        var val = $(this).val(), allow = {
            'list': 1,
            'tree': 5,
        };
        $('#groups tr:gt(0)').show().slice(allow[val]).hide();

     }).filter(':checked').change();
    {{ filter.javascript() }}
});
</script>

{% endblock %}

app/templates/views/tree.html
{% extends "views/base.full-width.html" %}

{% block css %}
{{ super() }}
<style>
.jstree-default.jstree-focused {
    background-color: #fff !important;
}
ins.jstree-icon.card {
    background-image: url(/static/bootstrap/img/glyphicons-halflings.png);
    background-position: -312px -72px !important;
}
</style>
{% endblock %}

{% block js %}
{{ super() }}
<script src="/static/jstree/jquery.jstree.js"></script>
<script type="text/javascript" src="/static/jstree/_lib/jquery.hotkeys.js"></script>
<script>
$(function() {
    var tree = $('#canvas');
    tree.on('tags', 'li', function(e, tags, added, removed) {
        e.stopPropagation();
        var updated = _.union(added, removed);
        var instance = $.jstree._reference(tree);
        _.each(updated, function(t) {
            tree.find('li.jstree-open[data-tag-id=' + t.tag_id + ']').each(function() {
                // Funny that instance.refresh(); restores all opened nodes successfully
                instance.refresh(this);
            });
        });
    }).on('clean_node.jstree', function (e, data) {
        data.rslt.obj.filter('[data-href]:not(:has(i.caret))').each(function() {
            $('<i />').addClass('caret').appendTo(this);
            $(this).addClass('has-caret');
        });
    }).jstree({
        'plugins' : ['themes', 'json_data', 'ui', 'hotkeys', 'dnd', 'crrm'],
        {# disable rename and remove key events #}
        'hotkeys': {
            'f2': false,
            'del': false
        },
        'crrm': {
            'move': {
                'check_move': function(m) {
                    {# dragging a tag || dropping into a card  #}
                    if ($(m.o).data('tag-id') || (!$(m.r).data('tag-id') && m.p == 'inside')) {
                        return false;
                    }
                    return true;
                }
            }
        },
        'json_data': {
            'data': {{ view.get_nodes(0)|tojson|safe }},
            'ajax' : {
                'data': function(node) {
                    // get path
                    var p = [];

                    node.parentsUntil('.jstree', 'li').each(function () {
                        p.push($(this).data('id'));
                    });

                    p.reverse();
                    p.push(node.data('id'));
                    var data = node.data();
                    data['values'] = p;

                    return data;
                },
                'url' : '{{ url_for('views.tree', id=view.id) }}'
            }
        }
    });
});
</script>
{% endblock %}
{% block tag_click_return %}e.preventDefault();{% endblock %}