app/tags/models.py
from sqlalchemy import Boolean, Column, ForeignKey, Integer, String
from sqlalchemy.orm import relationship, backref
from sqlalchemy.schema import UniqueConstraint

from ..database import Base

class Tag(Base):
    '''Tag is a something...

    :param id: the primary key
    :type id: int
    :param name: name of the tag
    :type name: str
    :param multiple: this tag can be appeared more than once in a card
    :type name: bool
    :param required: this tag is required in a card
    :type name: bool
    :param read_only: this tag is system generated, and cannot be edited
    :type name: bool

    '''
    __tablename__ = 'tag'

    id = Column(Integer, primary_key=True)
    name = Column(String, unique=True)
    multiple = Column(Boolean, default=False)
    required = Column(Boolean, default=False)
    read_only = Column(Boolean, default=False)

    values = relationship('TagValue', backref=backref('tag', order_by=id), lazy='dynamic')

    __mapper_args__ = {
        'order_by': 'name',
    }

    def __json__(self):
        return {'id': self.id, 'value': self.name }

    def __str__(self):
        return '{0}'.format(self.name)

class TagValue(Base):
    '''TagValue is set of Tag and its values

    :param id: the primary key
    :type id: int
    :param tag_id: foreign key to :class:`tags.models.Tag`
    :type tag_id: int
    :param value: value of the tag
    :type name: str

    The (Tag, Value) pair has to be unique.
    '''
    __tablename__ = 'tag_value'

    id = Column(Integer, primary_key=True)
    tag_id = Column(Integer, ForeignKey('tag.id'), nullable=False)
    value = Column(String)
    trello_id = Column(String, nullable=True, default=None)

    __table_args__ = (UniqueConstraint('tag_id', 'value', 'trello_id'), )
    __mapper_args__ = {
        'order_by': ['tag_id', 'value'],
    }

    def __str__(self):
        return '{0.tag.name}: {0.value}'.format(self)

    def __json__(self):
        return {'id': self.id, 'tag': self.tag.name, 'value': self.value,
                'tag_id': self.tag_id, 'tag_value': str(self)}

    def tree_data(self):
        ''' Returns a dict which represent the following
        {
            "data" : "node_title",
            // omit `attr` if not needed; the `attr` object gets passed to the jQuery `attr` function
            "attr" : { "id" : "node_identificator", "some-other-attribute" : "attribute_value" },
            // `state` and `children` are only used for NON-leaf nodes
            "state" : "closed", // or "open", defaults to "closed"
            "children" : [ /* an array of child nodes objects */ ]
        }
        {
            // `data` can also be an object
            "data" : { 
                "title" : "The node title", 
                // omit when not needed
                "attr" : {}, 
                // if `icon` contains a slash / it is treated as a file, used for background
                // otherwise - it is added as a class to the <ins> node
                "icon" : "folder"
            },

            // the `metadata` property will be saved using the jQuery `data` function on the `li` node
            "metadata" : "a string, array, object, etc",

            // if you use the language plugin - just set this property
            // also make sure that `data` is an array of objects
            "language" : "en" // any code you are using
        }

        '''
        return dict(data=str(self), state='closed',
                    attr={'data-id': self.id, 'data-tag-id': self.tag_id,
                          'data-tag': self.tag.name, 'data-value': self.value})

app/tags/forms.py
from flask.ext import wtf
from flask.ext.wtf import validators

class TagForm(wtf.Form):
    ''' A form which represents :class:`tags.models.Tag`
    '''
    name = wtf.TextField('Tag', validators=[validators.Required(), validators.DataRequired()])
    required = wtf.BooleanField('Required')
    multiple = wtf.BooleanField('Multiple')

class TagValueForm(wtf.Form):
    ''' A form which represents :class:`tags.models.TagValue`
    '''
    value = wtf.TextField('Value', validators=[validators.Required(), validators.DataRequired()])

app/tags/views.py
from flask import Blueprint, abort
from flask import flash, redirect, render_template, request, url_for
from sqlalchemy.exc import IntegrityError

import config
from . import forms
from .models import Tag, TagValue

from ..database import db_session
from ..helpers import get_or_404

mod = Blueprint('tags', __name__, url_prefix='/tags')

@mod.route('/')
def index():
    return render_template('tags/index.html', tags=Tag.query)

@mod.route('/new', methods=['GET', 'POST'])
def new():
    return edit()

@mod.route('/<int:tag>/edit', methods=['GET', 'POST'])
def edit(tag=None):
    is_add = tag is None

    if is_add:
        tag = Tag()
        form = forms.TagForm(request.form)
        template = 'tags/new.html'
    else:
        tag = get_or_404(Tag, Tag.id==tag)
        # this can be rewritten as tag = get_or_404(Tag, Tag.id==tag, Tag.read_only==False)
        if tag.read_only:
            abort(404)
        form = forms.TagForm(request.form, tag)
        template = 'tags/edit.html'

    if form.validate_on_submit():
        form.populate_obj(tag)
        try:
            if is_add:
                db_session.add(tag)
            db_session.commit()
            return redirect(url_for('tags.index'))

        except IntegrityError:
            db_session.rollback()

    return render_template(template, form=form, tag=tag)

@mod.route('/<int:tag>/values')
def values(tag):
    tag = get_or_404(Tag, Tag.id==tag)

    return render_template('tags/index.html', tags=Tag.query, tag=tag)

@mod.route('/<int:tag>/values/<int:value>/edit', methods=['GET', 'POST'])
def edit_value(tag, value=None):
    return new_value(tag, value)

@mod.route('/<int:tag>/values/new', methods=['GET', 'POST'])
def new_value(tag, value=None):
    tag = get_or_404(Tag, Tag.id==tag)
    # this can be rewritten as tag = get_or_404(Tag, Tag.id==tag, Tag.read_only==False)
    if tag.read_only and not config.DEBUG:
        abort(404)

    is_add = value is None

    if is_add:
        tagvalue = TagValue(tag=tag)
        form = forms.TagValueForm(request.form)
        template = 'tags/new-value.html'
    else:
        if config.DEBUG:
            tagvalue = get_or_404(TagValue, Tag.id==tag.id, TagValue.id==value)
        else:
            tagvalue = get_or_404(TagValue, Tag.read_only==False, Tag.id==tag.id,
                                            TagValue.id==value)
        form = forms.TagValueForm(request.form, tagvalue)
        template = 'tags/edit-value.html'

    if form.validate_on_submit():
        form.populate_obj(tagvalue)
        try:
            if is_add:
                db_session.add(tagvalue)

            db_session.commit()
            return redirect(url_for('tags.values', tag=tag.id))

        except IntegrityError:
            db_session.rollback()
            flash('Value "{0}" for {1} already exists.'.format(form.value.data, tag.name), 'error')

    return render_template(template, form=form, tag=tag, tagvalue=tagvalue)

app/templates/tags/edit-value.html
{% extends "tags/new-value.html" %}
{% block title %}Edit value for {{ tag.name }}{% endblock %}
{% block form_action %}{{ url_for('tags.edit_value', tag=tag.id, value=tagvalue.id) }}{% endblock %}

app/templates/tags/edit.html
{% extends "tags/new.html" %}
{% block title %}Edit Tag{% endblock %}
{% block form_action %}{{ url_for('tags.edit', tag=tag.id) }}{% endblock %}

app/templates/tags/index.html
{% extends "base.fixed-width.html" %}

{% block content %}
<h2>Manage Tags</h2>
<div class="row">
    <div class="span6">
        <table class="table table-striped">
            <thead><tr>
                <th>Tag</th>
                <th>Required</th>
                <th>Multiple</th>
                <th><i class="icon-cog"></i></th>
            </tr></thead>
            <tbody>
{% for t in tags %}
                <tr>
                    <td><a href="{{ url_for('tags.values', tag=t.id) }}">{{ t.name }}</a></td>
                    <td>{% if t.required %}<i class="icon-ok"></i>{% endif %}</td>
                    <td>{% if t.multiple %}<i class="icon-ok"></i>{% endif %}</td>
                    <td>
                        <a href="{{ url_for('tags.values', tag=t.id) }}" class="btn btn-mini">Values</a>
                        <a href="{% if t.read_only %}#{% else %}{{ url_for('tags.edit', tag=t.id) }}{% endif %}" class="btn btn-mini{% if t.read_only %} disabled{% endif %}">Update</a>
                    </td>
                </tr>
{% endfor %}
            </tbody>
        </table>
    </div>
    {% if tag %}
    {% if debug and tag.read_only %}
    {% set show_trello_id = True %}
    {% endif %}
    <div class="span6">
        <table class="table table-striped">
            <thead><tr>
                <th>Value for "{{ tag.name }}"</th>
                {% if show_trello_id %}
                <th>Trello ID</th>
                {% endif %}
                <th><i class="icon-cog"></i></th>
            </tr></thead>
            <tbody>
{% for v in tag.values %}
                <tr>
                    <td>{{ v.value }}</td>
                    {% if show_trello_id %}
                    <td>{{ v.trello_id }}</td>
                    {% endif %}
                    <td><a href="{{ url_for('tags.edit_value', tag=tag.id, value=v.id) }}" class="btn btn-mini{% if tag.read_only %}{% if not debug %} disabled{% endif %}{% endif %}">Update</a></td>
                </tr>
{% else %}
                <tr><td colspan="{% if show_trello_id %}3{% else %}2{% endif %}"><em>Empty values. Please add a value.</em></td></tr>
{% endfor %}

            </tbody>
        </table>
    </div>
    {% endif %}
</div>
<div class="row">
    <div class="span6"><a class="btn" href="{{ url_for('tags.new') }}">New Tag</a></div>
    {% if tag and not tag.read_only %}
    <div class="span6"><a class="btn" href="{{ url_for('tags.new_value', tag=tag.id) }}">New Value</a></div>
    {% endif %}
</div>
{% endblock %}

app/templates/tags/new-value.html
{% extends "base.fixed-width.html" %}

{% block content %}
<h2>{% block title %}New value for {{ tag.name }}{% endblock %}</h2>
{% from "forms/macros.html" import render_field %}
<form method="POST" action="{% block form_action %}{{ url_for('tags.new_value', tag=tag.id) }}{% endblock %}" class="form-horizontal">
{{ form.csrf_token }}
{{ render_field(form.value) }}

<div class="control-group">
    <div class="controls"><input type="submit" value="Save" class="btn btn-primary"> <a href="{{ url_for('tags.values', tag=tag.id) }}" class="btn">Cancel</a></div>
</div>
</form>
{% endblock %}

app/templates/tags/new.html
{% extends "base.fixed-width.html" %}

{% block content %}
<h2>{% block title %}New Tag{% endblock %}</h2>
{% from "forms/macros.html" import render_field %}
<form method="POST" action="{% block form_action %}{{ url_for('tags.new') }}{% endblock %}" class="form-horizontal">
{{ form.csrf_token }}
{{ render_field(form.name) }}
{{ render_field(form.required) }}
{{ render_field(form.multiple) }}

<div class="control-group">
    <div class="controls"><input type="submit" value="Save" class="btn btn-primary"> <a href="{{ url_for('tags.index') }}" class="btn">Cancel</a></div>
</div>
</form>
{% endblock %}