app/cards/views.py
import celery
from flask import Blueprint, abort
from flask import flash, redirect, render_template, request, session, url_for
from formencode import validators
from sqlalchemy.orm.exc import NoResultFound
import trello
from werkzeug.datastructures import ImmutableMultiDict

import config
import tasks

from . import forms
from .models import Card
from ..tags.models import Tag, TagValue

from ..helpers import get_or_404, get_or_create, jsonify
from ..database import db_session

mod = Blueprint('cards', __name__, url_prefix='/cards')

@mod.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST': # ajax request for new post
        return edit(None)
    return redirect(url_for('views.all_cards'))

@mod.route('/new')
def new(id=None):
    if id is None:
        card = Card()
    else:
        card = get_or_404(Card, Card.id==id)
    return render_template('cards/new.html', card=card)

@mod.route('/<int:id>')
def view(id):
    return new(id)

@mod.route('/<int:id>', methods=['POST', 'PUT'])
def edit(id=None):
    is_new = id is None
    ret = dict()

    if request.json:
        json = [(k, v if v else '') for k, v in request.json.iteritems()]

        for t in request.json.get('tags', []) or []:
            json.append(('tag_values', unicode(t)))

        try: # if is_complete checkbox is unchecked, remove it from the list
            json.remove(('is_complete', ''))
        except ValueError:
            pass

        data = ImmutableMultiDict(json)
    else:
        data = request.form

    if is_new:
        card = Card()
        form = forms.CardForm(data, csrf_enabled=False)
    else:
        card = get_or_404(Card, Card.id==id)
        form = forms.CardForm(data, card, csrf_enabled=False)

    if form.validate_on_submit():
        form.populate_obj(card)

        if is_new:
            db_session.add(card)
            db_session.commit()
            ret['created'] = True
        else:
            with db_session.suppress_events():
                db_session.commit()

            card.stream('sync')
            ret['updated'] = True

            if card.trello_id:
                token = session['access_token']['oauth_token']
                tasks.send_changes.delay(token, card.id)

        ret['id'] = card.id
    else:
        ret['error'] = form.errors

    return jsonify(**ret)

@mod.route('/<int:id>', methods=['DELETE'])
def delete(id):
    db_session.delete(get_or_404(Card, Card.id==id))
    db_session.commit()

    return jsonify(id=id, removed=True)

@mod.route('/<int:id>/tags', methods=['POST', 'GET'])
def tags(id):
    card = get_or_404(Card, Card.id==id)
    ret = {}

    def _json(tvs):
        return [tv.__json__() for tv in tvs]

    if request.method == 'POST':
        added = []
        removed = []

        # TODO?: make these as a separate form?
        attach = validators.StringBool().to_python(request.form['attach'])
        tag_value_id = validators.Int().to_python(request.form['id'])
        has_tag = False

        try:
            tv = card.tag_values.filter(TagValue.id == tag_value_id).one()
            has_tag = True
        except NoResultFound:
            tv = get_or_404(TagValue, TagValue.id == tag_value_id)

        l = card.items()

        if attach and not has_tag: # add exists tag value
            card.tag_values.append(tv)
            l.append(('tag_values', unicode(tv.id)))
            added.append(tv)
        elif not attach and has_tag: # remove new tag value
            card.tag_values.remove(tv)
            l.remove(('tag_values', unicode(tv.id)))
            removed.append(tv)

        # use `app.cards.forms.CardForm` to check tag requirements
        # (required or singularity)
        form = forms.CardForm(ImmutableMultiDict(l), csrf_enabled=False)

        if not form.validate():
            db_session.rollback()
            abort(400, form.errors)

        with db_session.suppress_events():
            db_session.commit()

        card.stream('sync')
        ret['added'] = _json(added)
        ret['removed'] = _json(removed)

    ret['tags'] = _json(card.tag_values)

    return jsonify(**ret)

@mod.route('/<int:id>/check_for_change', methods=['POST'])
def check_for_change(id):
    card = get_or_404(Card, Card.id==id)
    if card.trello_id:
        token = session['access_token']['oauth_token']
        tasks.check_for_change.delay(token, id)
    return jsonify(checking=True)

# a trello diction which stores (id, type)
# NOTE: cache should be managed per organization
_trello_cache =  {}
_trello_type = { 'organization': 1, 'board': 2, 'list': 4, 'card': 8 }
# stores value: key dict for lookup
_trello_type_vk = dict([(v, k) for k, v in _trello_type.iteritems()])

@mod.route('/import', methods=['POST', 'GET'])
def import_():
    token = session['access_token']['oauth_token']

    if request.method == 'POST':
        items = request.form.getlist('items')

        if not items:
            flash('Please check at least one item', 'error')
            return redirect(url_for('.import_'))

        for i in items:
            if i not in _trello_cache:
                flash('Invalid item', 'error')
                return redirect(url_for('.import_'))

        # probably good idea to move this to somewhere else...
        # Maybe on new Org?
        _, board_tag = get_or_create(Tag, name='Board', read_only=True)
        _, list_tag = get_or_create(Tag, name='List', read_only=True)
        db_session.add_all([board_tag, list_tag])
        db_session.commit()

        _task = tasks.import_cards.subtask
        flash('Scheduled importing...')
        g = celery.group(_task((token, i, _trello_type_vk[_trello_cache[i]])) for i in items)
        g.apply_async()

        return redirect(url_for('views.all_cards'))

    nodes = []

    client = trello.TrelloClient(config.TRELLO_API_KEY, token)
    orgs = client.fetch_json('/members/me/organizations')
    boards = client.fetch_json('/members/me/boards',
                               query_params={'filter': 'members'})

    for o in orgs:
        d = dict(attr={'id': o['id']},
                 data={'icon': 'organization', 'title': o['displayName']},
                 state='closed')

        if config.DEBUG:
            d['dump'] = o

        nodes.append(d)
        _trello_cache[o['id']] = _trello_type['organization']

    for b in boards:
        if b['idOrganization']:
            continue

        d = dict(attr={'id': b['id']},
                 data={'icon': 'board', 'title': b['name']},
                 state='closed', dump=b)

        if config.DEBUG:
            d['dump'] = b

        nodes.append(d)
        _trello_cache[b['id']] = _trello_type['board']

    return render_template('cards/import.html', nodes=nodes)

@mod.route('/import/child_nodes')
def import_child_nodes():
    id = request.args.get('id', None)

    if id is None or id not in _trello_cache:
        abort(404)

    client = trello.TrelloClient(config.TRELLO_API_KEY,
                                 session['access_token']['oauth_token'])
    _type = _trello_cache[id]

    if _type == _trello_type['organization']:
        url = '/organization/{0}/boards'
        _fetch_type = 'board'
    elif _type == _trello_type['board']:
        url = '/board/{0}/lists'
        _fetch_type = 'list'
    elif _type == _trello_type['list']:
        url = '/list/{0}/cards'
        _fetch_type = 'card'
    else:
        abort(404)

    data = client.fetch_json(url.format(id))
    nodes = []

    for d in data:
        di = dict(attr={'id': d['id']},
                  data={'icon': _fetch_type, 'title':d['name']})

        if _trello_type[_fetch_type] != _trello_type['card']:
            di['state'] = 'closed'

        if config.DEBUG:
            di['dump'] = d

        _trello_cache[d['id']] = _trello_type[_fetch_type]

        nodes.append(di)

    return jsonify(nodes)

app/views/views.py
from flask import Blueprint, abort
from flask import redirect, render_template, request, url_for

from formencode import validators

from . import forms
from .models import View, Group, Filter

from ..cards.models import Card
from ..filters.forms import FilterForm

from ..database import db_session
from ..helpers import get_or_404, jsonify

mod = Blueprint('views', __name__, url_prefix='/views')

@mod.route('/')
def index():
    views = View.query
    return render_template('views/index.html', views=views)

@mod.route('/<int:id>')
def view(id):
    view = get_or_404(View, View.id==id)

    if view.type == 'tree':
        return view_tree(view)
    elif view.type == 'list':
        return view_list(view)

    return abort(404)

def view_tree(view):
    return render_template('views/tree.html', view=view, order=forms.order)

def view_list(view):
    return render_template('views/list.html', view=view, order=forms.order)

@mod.route('/<int:id>/tree')
def tree(id):
    ''' ajax request from jstree to get nodes at a given level'''
    validator = validators.Int()

    view = get_or_404(View, View.id==id)
    level = validator.to_python(request.args['level'])
    parents = [validator.to_python(p) for p in request.args.getlist('values[]')]
    tags = view.get_nodes(level+1, parents=parents)

    return jsonify(tags)

@mod.route('/all-cards')
def all_cards():
    filter_ = FilterForm(request.args)
    q = filter_.prepare_query(Card.query)
    return render_template('views/all-cards.html', cards=q, filter=filter_)

@mod.route('/new', methods=['GET', 'POST'])
def new(id=None):
    is_new = id is None
    if is_new:
        view = View()
        form = forms.ViewForm(request.form)
    else:
        view = get_or_404(View, View.id==id)
        form = forms.ViewForm(request.form, view)

    filter_ = FilterForm(request.form if request.form else view.get_filter_dict(), allow_empty=True)

    if form.validate_on_submit():
        form.populate_obj(view)

        if not is_new:
            # to make it simple, just remove all groups assigned to this view
            # otherwise, call views.groups.append(g) views.filters.remove(f)
            Group.query.filter(Group.view_id == view.id).delete()
            Filter.query.filter(Filter.view_id == view.id).delete()

        for i, o in enumerate(forms.order):
            try:
                data = form.groups.data[o.lower()]
                if not data:
                    continue

                g = Group()
                g.tag = data
                g.order = i
                view.groups.append(g)
            except KeyError:
                pass

        for i, p in enumerate(filter_.values['filters']):
            f = Filter()
            f.key = p['key']
            f.condition = p['condition']
            f.values = dict(value=p['value'], value_start=p['value_start'], value_finish=p['value_finish'])
            f.order = i
            view.filters.append(f)

        if is_new:
            db_session.add(view)

        db_session.commit()
        return redirect(url_for('.view', id=view.id))

    return render_template('views/new.html', filter=filter_, form=form, view=view)

@mod.route('/<int:id>/edit', methods=['GET', 'POST'])
def edit(id):
    return new(id)

@mod.route('/<int:id>', methods=['DELETE'])
@mod.route('/<int:id>/delete')
def delete(id):
    v = get_or_404(View, View.id==id)
    db_session.delete(v)
    db_session.commit()

    return redirect(url_for('.index'))

app/templates/base.fixed-width.html
{% extends "base.html" %}
{% block body %}
<div class="container">
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<br /><br />
{% for category, message in messages %}
<div class="alert {% if category == 'message' %}alert-info{% else %}alert-{{ category }}{% endif %}">{{ message }}</div>
{% endfor %}
{% endif %}
{% endwith %}
{% block content %}{% endblock %}
</div>
{% endblock %}

app/templates/base.full-width.html
{% extends "base.html" %}
{% block body %}
{% block content %}{% endblock %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>TaskCard</title>
{% block css %}
<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
<style>
.nav .new-card > a {
    display: inline-block;
    padding-right: 0 !important;
}
.nav .new-card > a.dropdown-toggle {
    padding-left: 8px !important;
    padding-right: 8px !important;
}
body {
    padding-top: 40px;
}
</style>
{% endblock %}
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <ul class="nav pull-right">
            {% if is_authenticated %}
            <li><a class='logout' href="{{ url_for('logout') }}">You are logged in as <span id="full_name">...</span></a></li>
            <li class="dropdown new-card">
                <a href="{{ url_for('cards.new') }}"><i class="icon-edit"></i> Create New Card</a>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{{ url_for('cards.new') }}">Create New Card</a></li>
                    <li><a href="{{ url_for('cards.import_') }}">Import Cards</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-th-large"></i> Views <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{{ url_for('views.all_cards') }}">All Cards</a></li>
                    <li class="divider"></li>
                    {% for v in all_views %}
                    <li><a href="{{ url_for('views.view', id=v.id) }}">{{ v.name }}</a></li>
                    {% endfor %}
                    <li class="divider"></li>
                    <li><a href="{{ url_for('views.new') }}">Create New Views</a></li>
                    <li><a href="{{ url_for('views.index') }}">Manage Views</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-cog"></i> Settings <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{{ url_for('tags.index') }}">Tags</a></li>
                    <li><a href="{{ url_for('views.index') }}">Views</a></li>
                    <li><a href="{{ url_for('users') }}">Users</a></li>
                </ul>
            </li>
            {% else %}
            <li><a href="{{ url_for('login') }}">Login with Trello</a></li>
            {% endif %}
        </ul>
    </div>
</div>

{% block body %}{% endblock %}

{% block bodyhelpers %}{% endblock %}

{% block js %}
{% if debug %}
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.js"></script>
{% else %}
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
{% endif %}
<script src="/static/underscore/underscore.js"></script>
<script src="/static/mustache/mustache.js"></script>
<script src="/static/backbone/backbone.js"></script>
<script src="/static/parsley/parsley.js"></script>
<script src="http://cdn.sockjs.org/sockjs-0.3.min.js"></script>
<script>
{% raw %}
_.templateSettings = {
    evaluate: /\{\%(.+?)\%\}/g,
    interpolate: /\{\{(.+?)\}\}/g,
    escape: /\{\{-(.+?)\}\}/g
};
{% endraw %}
$(function() {
    {# escape {{ and }} #}
    {% raw %}
    $(document).ajaxError(function(e, xhr, settings, error) {
        var html = '<div class="modal hide fade" tabindex="-1" role="dialog"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h3>Error {{status}} -- {{statusText}}</h3></div><div class="modal-body"><p>{{responseText}}</p></div><div class="modal-footer"><button class="btn" data-dismiss="modal">Close</button></div></div>';
        $(Mustache.render(html, xhr)).appendTo('body').modal().on('hidden', function() {
            $(this).remove();
        });

    });
    {% endraw %}

    {% if is_authenticated %}
    window.stream = new SockJS('http://' + location.host  + location.pathname + '/streaming'{% if debug %}, null, {debug: true}{% endif %});
    stream.onopen = function(e) {
        console.log('open', e);
    };
    stream.onmessage = function(e) {
        console.log('message', e);
        var d = e.data;
        this.onmessage.trigger(d.type + ':' + d.action, d.data, e);
    };

    stream.onclose = function(e) {
        console.log('close', e);
    };

    {# extending onopen, onmessage and onclose to accept events #}
    _.each(['onopen', 'onmessage', 'onclose'], function (e) {
        _.extend(stream[e], Backbone.Events);
    });

    window.models = {};

    models.User = Backbone.Model.extend({
        defaults: {
            id: -1,
            trello_username: null,
            full_name: null,
            email: null,
        }
    });

    var me = new models.User();

    me.listenTo(stream.onmessage, 'me:sync', function(data) {
        me.set(data);
    });
    me.on('change:full_name', function() {
        $('#full_name').text(this.get('full_name'));
    });
    {% endif %}
});
</script>
{% endblock %}
</body>
</html>

app/templates/index.html
{% extends "base.fixed-width.html" %}

{% block content %}
<h1>Index</h1>
<p class="important">Welcome!. </p>
{% endblock %}

app/templates/welcome.html
{% extends "base.fixed-width.html" %}

{% block content %}
<h1>Welcome</h1>
<p class="important">You need to have a Trello login and authenticate with Trello before you continue.</p>
<div>
    <a href="{{ url_for('login') }}" class="btn btn-info">Login with Trello</a>
</div>
{% endblock %}